baseURL = "https://fervent-williams-59ddf6.netlify.com"
languageCode = "en-us"
title = "Ivan Sedelkin"
theme = "hugo-base-theme" 

[params]
  description = "I <3 making web site"
  mainIcon = "/img/hugo.png"
  custom_css = "/css/bootstrap-theme.css"

[[params.social]]
    title = "twitter"
    url = "https://twitter.com/SBootstrap"
[[params.social]]
    title = "github"
    url = "https://github.com/IronSummitMedia/startbootstrap"
[[params.social]]
    title = "linkedin"
    url = ""
