baseURL = "https://fervent-williams-59ddf6.netlify.com"
languageCode = "en-us"
title = "Ivan Sedelkin"
theme = "hugo-base-theme" 

[params]
    author = "Ivan Sedelkin"
    info = "Software Developer and 3D Artist"
    description = "Ivan Sedelkin's personal website"
    avatarurl = "images/ivan.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = "Personal website for personal advertising. I don't sell products here"

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social Links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/RyuTribal/"
[[params.social]]
    name = "StackOverFlow"
    icon = "fab fa-stack-overflow fa-2x"
    weight = 2
    url = "https://stackoverflow.com/users/10330648/ivan-sedelkin?tab=profile"
[[params.social]]
    name = "CGTrader"
    icon = "fas fa-palette fa-2x"
    weight = 3
    url = "https://www.cgtrader.com/ryutribal"
